apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/openshift-network-observability-operator/operator
  - ../../../../base/bpfman/operator
components:
  - ../../../../base/openshift-network-observability-operator/components/netobserv-v1.12.1
  - ../../../../base/bpfman/components/bpfman-v0.6.0
