apiVersion: tenantconfig.openshift.io/v1alpha1
kind: NamespaceResourceQuota
metadata:
  name: large
spec:
  hard:
    cpu: "16"
    memory: "64Gi"
    pods: "50"
    configmaps: "20"
    persistentvolumeclaims: "20"
    replicationcontrollers: "10"
    secrets: "30"
    services: "30"
    services.loadbalancers: "0"
