apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: ClusterLogForwarder
      name: instance
    patch: |-
      - op: add
        path: /spec/outputs
        value:
          - lokiStack:
              authentication:
                token:
                  from: serviceAccount
              target:
                name: logging-loki
                namespace: openshift-logging
            name: default-lokistack
            type: lokiStack
      - op: replace
        path: /spec/pipelines/0/outputRefs/0
        value: default-lokistack
