apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/openshift-loki-operator/operator
components:
  - ../../../../base/openshift-loki-operator/components/loki-v6.6.0
  - ../../../../base/openshift-loki-operator/components/instance-sizes/small
