apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/multi-tenant-operator/operator
  - ../../../../base/multi-tenant-operator/instance
components:
  - ../../../../base/multi-tenant-operator/components/mto-v0.2.1
