apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openshift-ingress-tls-secret
  namespace: openshift-ingress
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: bao-vault
    kind: ClusterSecretStore
  target:
    name: openshift-ingress-tls-secret
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: openshift-ingress-operator/ingress-tls
        property: tls.crt

    - secretKey: tls.key
      remoteRef:
        key: openshift-ingress-operator/ingress-tls
        property: tls.key
