apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../base/cluster-config/openshift-ingress/instances/default
  - ingress-tls-secret.yaml
patches:
  - target:
      kind: IngressController
      name: default
    path: patch-ingress.yaml
