apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: Subscription
      name: lvms-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: stable-4.21
      - op: replace
        path: /spec/startingCSV
        value: lvms-operator.v4.21.0
