apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: Subscription
      name: kubevirt-hyperconverged
    patch: |-
      - op: replace
        path: /spec/channel
        value: stable-4.21
      - op: replace
        path: /spec/startingCSV
        value: odf-operator.v4.21.1-rhodf
