apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-s3
  namespace: netobserv
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: openshift-loki/s3
      metadataPolicy: None
      nullBytePolicy: Ignore
      property: secret_key
    secretKey: access_key_secret
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: openshift-loki/s3
      metadataPolicy: None
      nullBytePolicy: Ignore
      property: access_key
    secretKey: access_key_id
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: openshift-loki/s3
      metadataPolicy: None
      nullBytePolicy: Ignore
      property: endpoint
    secretKey: endpoint
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: openshift-loki/s3
      metadataPolicy: None
      nullBytePolicy: Ignore
      property: bucket
    secretKey: bucketnames
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: openshift-loki/s3
      metadataPolicy: None
      nullBytePolicy: Ignore
      property: region
    secretKey: region
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: bao-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: loki-s3
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
