apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../base/cluster-config/openshift-oauth/instance
  - oidc-secret.yaml
components:
  - ../../../../../base/cluster-config/openshift-oauth/components/oidc
patches:
  - target:
      kind: OAuth
      name: cluster
    path: patch-oauth.yaml
