apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: Subscription
      name: bpfman-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: stable
      - op: replace
        path: /spec/startingCSV
        value: bpfman-operator.v0.6.0
