apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namespace: openshift-config
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: cloudflare-origin-ca
    files:
      - ca-bundle.crt=cloudflare-origin-ca.pem
patches:
  - target:
      kind: Proxy
      name: cluster
    path: patch-proxy.yaml
