apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/compliance-operator/controller

components:
  - ../../../../base/compliance-operator/components/controller-1-8
