apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: Subscription
      name: kubernetes-nmstate-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: stable
      - op: replace
        path: /spec/startingCSV
        value: kubernetes-nmstate-operator.4.22.0-202607011224
