apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: Subscription
      name: multi-tenant-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: alpha
      - op: replace
        path: /spec/startingCSV
        value: multi-tenant-operator.v0.2.1
