apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: argocd-app-of-apps
    repo: oci://ghcr.io/redhat-consulting-services/helm-charts
    version: 1.3.2
    releaseName: app-of-apps
    valuesFile: ./tenant-helm-values.yaml

  - name: argocd-app-of-apps
    repo: oci://ghcr.io/redhat-consulting-services/helm-charts
    version: 1.3.2
    releaseName: app-of-apps
    valuesFile: ./mto-values.yaml
