appSuffix: hcp1
appSourceBasePath: overlays/hcp1/cluster-config

default:
  application:
    enabled: false
    namespace: "openshift-gitops"
    labels: {}
    annotations: {}
    finalizers: []
    destination:
      server: https://kubernetes.default.svc
      namespace: "openshift-gitops"
    project: "cluster-config-hcp1"
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
    source:
      repoURL: https://github.com/leonsteinhaeuser/openshift-cluster-config
      targetRevision: main

  project:
    enabled: false
    namespace: "openshift-gitops"
    annotations:
      argocd.argoproj.io/sync-wave: "-100000"
    sourceRepos:
      - '*'
    destinations:
      - namespace: '*'
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
    namespaceResourceWhitelist:
        - group: '*'
          kind: '*'

projects:
  cluster-config-hcp1:
    enabled: true
    description: "Project for cluster configuration of HCP1 cluster"

applications:
  cluster-config-proxy:
    enabled: true
    annotations:
      argocd.argoproj.io/sync-wave: "-10"
    source:
      path: "base-config/proxy"
    extraFields:
      ignoreDifferences:
        - kind: ConfigMap
          name: openshift-user-ca
        - kind: ConfigMap
          name: user-ca-bundle
          jsonPointers:
            - /data

  external-secrets-operator:
    enabled: true
    annotations:
      argocd.argoproj.io/sync-wave: "-9"
    source:
      path: "external-secrets-operator"

  openshift-gitops-operator:
    enabled: true
    annotations:
      argocd.argoproj.io/sync-wave: "-8"
    source:
      path: "openshift-gitops-operator"

  cluster-config-ingress:
    enabled: true
    annotations:
      argocd.argoproj.io/sync-wave: "-7"
    source:
      path: "base-config/ingress"

  cluster-config-oauth:
    enabled: true
    annotations:
      argocd.argoproj.io/sync-wave: "-6"
    source:
      path: "base-config/oauth"

  nmstate-operator:
    enabled: true
    annotations:
      argocd.argoproj.io/sync-wave: "0"
    source:
      path: "nmstate-operator"
