apiVersion: tenant.openshift.io/v1alpha1
kind: MultiTenantConfig
metadata:
  name: mto-light
  labels:
    access.network.openshift.io/default: ""
spec:
  resourceQuotaReference: small
  limitRangeReference: small
  argocd:
    instanceName: openshift-gitops
    instanceNamespace: openshift-gitops
    project:
      enabled: true
      name: mto-light
      destinations:
        - server: https://kubernetes.default.svc
          namespace: mto-light-front
        - server: https://kubernetes.default.svc
          namespace: mto-light-back
        - server: https://kubernetes.default.svc
          namespace: mto-light-center
        - server: https://kubernetes.default.svc
          namespace: mto-light-shared
      sourceRepos:
        - https://github.com/leonsteinhaeuser/openshift-cluster-config.git
      clusterResourceBlacklist:
        - group: '*'
          kind: '*'
      namespaceResourceBlacklist:
        - group: networking.k8s.io
          kind: NetworkPolicy
  configSpec:
    enableAuditLogging: true
    enableUserWorkloadMonitoring: true
    enableCertificateConfigMapCreation: true
    enableArgoCDControllerManagement: true
    enableNamePrefix: true
    enableNetworkPolicyTenantInternalAllow: true
  namespaces:
    - name: front
    - name: center
    - name: back
    - name: shared
