apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bao-vault
  namespace: external-secrets-operator
spec:
  provider:
    vault:
      server: "https://bao.k8scope.dev"
      path: "secrets"
      namespace: "hcp1-k8scope-dev"
      version: "v2"
      auth:
        appRole:
          path: "approle"
          roleId: "7b2d6818-f442-7d9e-2bd0-2069918b5e5a"
          secretRef:
            name: "open-bao-approle-token"
            namespace: "external-secrets-operator"
            key: "secretID"
