apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: master-02
spec:
  nodeSelector:
    kubernetes.io/hostname: master-02.hcp1.k8scope.dev
  desiredState:
    interfaces:
      - name: enp7s0
        type: ethernet
        state: up
        mac-address: 52:54:00:30:22:0e
        ipv4:
          enabled: true
          dhcp: false
          address:
            - ip: 192.168.100.11
              prefix-length: 24
