apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: master-01
spec:
  nodeSelector:
    kubernetes.io/hostname: master-01.hcp1.k8scope.dev
  desiredState:
    interfaces:
      - name: enp7s0
        type: ethernet
        state: up
        mac-address: 52:54:00:af:e9:1a
