apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: custom-ca-bundle
  namespace: openshift-config
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: bao-vault
    kind: ClusterSecretStore
  target:
    name: custom-ca-bundle
  data:
  - secretKey: ca-bundle.crt
    remoteRef:
      key: openshift-config/user-ca-bundle
      property: ca-bundle.crt
