apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../base/cluster-config/openshift-proxy/instance
components:
  - ../../../../../base/cluster-config/openshift-proxy/components/cloudflare-origin-ca-root
