apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/external-secrets-operator/operator

components:
  - ../../../../base/external-secrets-operator/components/external-secrets-operator-1.0
