apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/loki-operator/operator
  - ../../../../base/loki-operator/instance

components:
  - ../../../../base/loki-operator/components/loki-6.4
  - ../../../../base/loki-operator/components/sizes/small
