apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 99-master.yaml
  - 99-worker.yaml
patches:
  - target:
      kind: KubeletConfig
      name: 99-master-kubelet-config
    path: components/kubelet-config.yaml
  - target:
      kind: KubeletConfig
      name: 99-worker-kubelet-config
    path: components/kubelet-config.yaml
