apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: Subscription
      name: advanced-cluster-management
    patch: |-
      - op: replace
        path: /spec/channel
        value: release-2.16
      - op: replace
        path: /spec/startingCSV
        value: advanced-cluster-management.v2.16.0
