apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/vault/instance

components:
  - ../../../../base/vault/components/vault-1.21

patches:
  - target:
      kind: Route
      name: vault
    path: patch-route.yaml
