name: Kustomize Validation

on:
  push:
    branches:
      - "**"

env:
  IMAGE_REPOSITORY: quay.io/redhat-consulting-services/kustomize-validator

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup kustomize-validator
        run: |
          mkdir tmp
          cd tmp
          curl -X GET -L https://github.com/redhat-consulting-services/kustomize-validator/releases/download/v1.1.0/kustomize-validator_Linux_x86_64.tar.gz -o kustomize-validator.tar.gz
          tar -xzf kustomize-validator.tar.gz

      - name: Execute Kustomize Validator
        run: |
          ./tmp/kustomize-validator ./overlays --table
