name: Kustomize Validation

on:
  push:
    branches:
      - "**"

env:
  IMAGE_REPOSITORY: quay.io/redhat-consulting-services/kustomize-validator

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Debug path
        run: |
          echo "Workspace: ${{ github.workspace }}"
          echo "-------------------------------"
          ls -l "${{ github.workspace }}"
          echo "-------------------------------"
          ls -l "./"

      - name: Execute Kustomize Validator
        run: docker run --rm --entrypoint '/kustomize-validator --help' -v "./:/data" ${{ env.IMAGE_REPOSITORY }}:latest
